import type { Project } from "@/types/project";

/** Public source reviewed 2026-09-09; see the dated repository review. */
export const githubProjects: Project[] = [
  {
    slug: "ai-brand-tracker",
    name: "Thailand AI Market Intelligence",
    displayTitle: "วัดการมองเห็นแบรนด์ โดยแยกคำตอบ AI ออกจากอันดับผลค้นหา",
    kind: "Analytics application",
    status: "EXPERIMENTAL",
    summary: "A Python/FastAPI application that collects brand observations, stores their provenance in DuckDB, and compares results by answer surface.",
    context: "A brand may appear in an AI recommendation, an organic search result, or a retrieved citation. Those observations answer different questions.",
    problem: "Comparing visibility across providers is misleading when generative answers and search rankings are blended into one metric.",
    impact: "Makes each observation traceable to a provider, query and run, with separate metrics for generative answers and search results.",
    constraints: ["Public implementation with live-provider adapters and explicitly synthetic demo modes; production adoption is not established.", "The committed screenshot is labelled Serper: its search rankings are not evidence of generative-AI recommendations or market leadership."],
    input: ["Configured brands and aliases", "Thai consumer-intent queries and personas", "Provider responses or deterministic mock observations"],
    system: ["Generate queries and route them through a provider adapter.", "Persist observations, brand mentions and citations with run identifiers in DuckDB.", "Reload persisted observations for surface-specific metrics, API responses and the web dashboard."],
    decisions: [
      { title: "Separate the answer surfaces", why: "A search-result position should not inflate a metric intended to describe generative recommendations." },
      { title: "Analyze the persisted record", why: "Reading back from the canonical store makes persistence failures visible and keeps API results traceable to a run." },
      { title: "Make synthetic mode explicit", why: "Deterministic mock observations help exercise the workflow but cannot support a business conclusion." },
    ],
    implementation: ["Query generation, provider adapters, DuckDB storage, analytics modules and a FastAPI dashboard backend.", "Committed tests cover storage, engine behavior, analytics, API contracts and pipeline integration."],
    stack: ["Python", "FastAPI", "DuckDB", "Pydantic", "Provider APIs"],
    evidence: [
      { class: "VERIFIED_CODE", label: "Collection, persistence and analytics orchestration", sourcePath: "src/runner.py", sourceUrl: "https://github.com/adulsaa-q/ai_brand_tracker/blob/main/src/runner.py" },
      { class: "VERIFIED_CODE", label: "DuckDB schema and observation storage", sourcePath: "src/storage/duckdb_store.py", sourceUrl: "https://github.com/adulsaa-q/ai_brand_tracker/blob/main/src/storage/duckdb_store.py" },
      { class: "VERIFIED_TEST", label: "Committed pipeline integration tests", sourcePath: "tests/test_pipeline_integration.py", sourceUrl: "https://github.com/adulsaa-q/ai_brand_tracker/blob/main/tests/test_pipeline_integration.py", note: "Source inspection; the portfolio audit did not execute paid-provider calls." },
      { class: "VERIFIED_ARTIFACT", label: "Committed Serper dashboard capture", sourcePath: "docs/assets/dashboard.png", sourceUrl: "https://github.com/adulsaa-q/ai_brand_tracker/blob/main/docs/assets/dashboard.png" },
      { class: "README_REPORTED", label: "Feature status and remaining gaps", sourcePath: "docs/STATUS.md", sourceUrl: "https://github.com/adulsaa-q/ai_brand_tracker/blob/main/docs/STATUS.md" },
    ],
    limitations: ["Live-key integration tests and production hardening remain gaps in the source status document.", "Scan job state is in-process. Recommendations and the what-if simulator are not validated business-impact forecasts.", "The screenshot's market-leadership wording exceeds what its small Serper sample establishes; the portfolio does not endorse that claim."],
    artifacts: [{ type: "SCREENSHOT", src: "/images/ai-brand-tracker/dashboard.png", alt: "Committed Thailand AI Market Intelligence dashboard screenshot, labelled Serper with twelve queries and search-result brand rankings.", caption: "Source screenshot: Serper search observations. Its market-leadership wording is not a verified outcome, and this is not a live portfolio dashboard.", reconstructed: false }],
    services: ["Analytics applications", "API integration", "Data modeling"],
    repository: "https://github.com/adulsaa-q/ai_brand_tracker",
  },
  {
    slug: "ai-command-center",
    name: "AI Command Center",
    displayTitle: "กำหนดขอบเขตงาน ความจำ และการส่งต่องานสำหรับ AI coding workflows",
    kind: "Engineering framework",
    status: "EXPERIMENTAL",
    summary: "A documented operating model with workspace templates, a SQLite record schema and small Python utilities for coordinating AI-assisted engineering.",
    context: "Shared AI workspaces can accumulate conflicting instructions, stale handoffs and unclear ownership of files.",
    problem: "Long-running engineering work needs a clear place for permanent rules, current task state and records of what happened.",
    impact: "Provides a concrete starting structure for task ownership, handoffs, documentation freshness and recorded changes.",
    constraints: ["Public framework, templates and supporting utilities; not a deployed agent orchestration service.", "Authority and append-only policies are documented conventions, not enforced security boundaries."],
    input: ["Workspace rules and architecture decisions", "Current task handoffs", "Commit, task and pipeline-run records"],
    system: ["Separate permanent rules, project decisions and rolling task memory.", "Define roles and change classes in Markdown templates.", "Provide SQLite tables for records and Python utilities for document-age checks and advisory lock files."],
    decisions: [
      { title: "Keep permanent rules outside rolling memory", why: "A handoff can expire without discarding the workspace's long-lived constraints." },
      { title: "Use plain files and SQLite", why: "The structure can be inspected and adapted without requiring a hosted coordination platform." },
      { title: "Document authority separately from evidence", why: "A record of a change describes what happened; it does not itself grant permission for another change." },
    ],
    implementation: ["Markdown architecture and role documents, starter workspace templates, six SQLite tables and two Python utilities."],
    stack: ["Markdown", "SQLite", "Python", "Git"],
    evidence: [
      { class: "README_REPORTED", label: "Architecture and operating model", sourcePath: "docs/ARCHITECTURE.md", sourceUrl: "https://github.com/adulsaa-q/ai-command-center/blob/main/docs/ARCHITECTURE.md" },
      { class: "VERIFIED_CODE", label: "SQLite record schema", sourcePath: "templates/.remember/schema.sql", sourceUrl: "https://github.com/adulsaa-q/ai-command-center/blob/main/templates/.remember/schema.sql" },
      { class: "VERIFIED_CODE", label: "Documentation staleness checker", sourcePath: "tools/check_doc_staleness.py", sourceUrl: "https://github.com/adulsaa-q/ai-command-center/blob/main/tools/check_doc_staleness.py" },
      { class: "VERIFIED_CODE", label: "Advisory lock-file utility", sourcePath: "tools/file_lock.py", sourceUrl: "https://github.com/adulsaa-q/ai-command-center/blob/main/tools/file_lock.py" },
    ],
    limitations: ["The SQLite schema does not enforce immutability through triggers or access controls.", "The lock helper checks then writes a file; it is not an atomic mutex or a guarantee against concurrent writes.", "Public files do not independently establish organization-wide adoption, productivity gains or production safety."],
    artifacts: [{ type: "SOURCE_REGISTER", alt: "SQL excerpt defining correlations between a source record and an artifact.", caption: "Excerpt from templates/.remember/schema.sql. This defines a record structure; append-only behavior is a policy rather than a constraint in this schema.", reconstructed: false, excerpt: "CREATE TABLE IF NOT EXISTS evidence_correlations (\n    correlation_id TEXT PRIMARY KEY,\n    source_type TEXT NOT NULL,\n    source_id TEXT NOT NULL,\n    related_artifact_path TEXT NOT NULL,\n    notes TEXT,\n    created_at TIMESTAMP NOT NULL\n);" }],
    services: ["Engineering workflow design", "Technical documentation", "Internal tooling"],
    repository: "https://github.com/adulsaa-q/ai-command-center",
  },
];
